### PR TITLE
[TEL-294] Improve CPU Utilization to improve Telehealth experience(web)

### PR DESCRIPTION
**Pull request by ivanjiang5628**
## Description
- [Jira Ticket](https://janeapp.atlassian.net/browse/TEL-294)

We were seeing high CPU utilization on some clients' machines. To resolve this issue we decided to disable/remove the following feature/settings:

- disabling H.264 codec (related to hardware acceleration) on the back-end side.

- disabling video backgrounds in FE.

- remove the `AudioLevelIndicator` component from `LargeVideo` & `RemoteVideo` component.

🏇 = Performance improvement

- [ ] requires env configuration to be added in production
- [ ] js package changes<sup>1</sup>
- [ ] more than 200 LOC changed in production files<sup>1</sup>
- [ ] includes a user-facing workflow change to an existing production feature (user muscle memory or pattern recognition will be affected)
- [ ] could prevent access to Jane Video (eg. cors, middleware, changes to auth system)
- [ ] affects a widely used component or piece of code
- [ ] I have a doubt - I want the RMT to review this. If possible, please elaborate your concerns in the risk assessment section.

<sup>1</sup> No need to explain these risk factors below

### Release Risk Assessment
Low

## Code Review
Resource: [Dev Team Notion Page](https://www.notion.so/janeapp/Dev-Team-f06c6eb2ccca4066bc63fc1ac1bd2549)
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)

- [x] I clearly explained the WHY behind the work, in the Description above

#### Design
- [x] I added instructions for how to test, in the QA section below
- [ ] I added tests for changes, or determined that none were required
- [x] I demoed this to the appropriate person
- [x] I considered both mobile & desktop views, or that wasn't relevant

#### Code
- [x] I committed code with informative git messages
- [x] I wrote readable code, or added comments if it was complex
- [x] I performed a self-review of my own code
- [x] I rebased my branch on the latest `master`
- [x] I confirmed that all CircleCI tests are passing
- [ ] I didn't add new npm packages, or else I made damn sure the `yarn.lock` changes are safe for existing production packages

### Steps to Reproduce

Please use `https://videochat.jane.qa/someroomname` for QA

- the video background(the blurry background) should be removed.

- the small video window would not show the audio level indicator(blue dots) when the user is speaking.

### Jitsi backend update

- set `disableH264=true` in `config.js` file (2 locations in config.js) for disabling H.264 codec (related to hardware acceleration)

## Before:

image

## After:

image

### CODE REVIEW

**Review by cwarren79 — APPROVED** [review]
Just wanted to note that the `interface_config.js` file included in the app bundle is the one that is used.

i.e. only config.js on the backend will need to be modified

**Review by cwarren79 — CHANGES_REQUESTED** [review]
Actually that means you'll have to add the necessary changes to interface_config.js in this PR

**Comment by ivanjiang5628** [comment]
> Actually that means you'll have to add the necessary changes to interface_config.js in this PR

Gotcha! PR updated

**Review by cwarren79 — APPROVED** [review]

**Review by gerbus — APPROVED** [review]

**Comment by jngo-janeapp** [comment]
## TELE-294 s14
## Before Testing
- [ ]  CI must be passing
- [ ]  No conflicts
- [ ]  No unresolved reviews/changes requested
- [ ]  No additional changes/pushes from dev since the last round of QA
- [ ]  Release note is sufficient for [#features](https://janeapp.slack.com/archives/C0KC1395G)
- [ ]  Read through Notion / Jira story / Linear Issue / Slack Convo / Demo video

## Developer's Recommended Test Plan
- [ ] Please use https://videochat.jane.qa/someroomname for QA
- [ ] The video background(the blurry background) should be removed.
- [ ] The small video window would not show the audio level indicator(blue dots) when the user is speaking.


## Additional Thoughts on Testing
- [ ] User can 

## Mobile, Browsers, Jane Desktop
- [ ]  Google Chrome
- [ ]  Safari
- [ ]  Firefox
- [ ]  Microsoft Edge
- [ ]  Jane Desktop
- [ ]  iPad Mini
- [ ]  iPhone

## Regression Testing / Exploratory
(Consider related areas or areas where data persists Ie. Chart Templates/Intake Forms, Chart Entries/Export to PDF, Reports / Export to CSV/xls, Payment / Receipts / Superbill(US))
- Can you export a PDF from this area/function?
- Can this functionality be reused somewhere else in Jane? Or does it share components with other areas in Jane. (Canadian & US Insurance)
- Does this area have an inverse setting? Enabled/Disabled, Beta Feature Flag
- Does this area have multiple setting types? Ie. Intake Forms, Permissions/Privacy, User types
- Does this correspond to an area in Online Booking? (Booking an appointment, Entering a credit card and paying for an appointment)
- Is this related to Payment Methods? Jane Payments: Stripe, Payfirma, Square Terminal, Cash, Gift Cards, Credit Memos, Account Credit, Packages
- Could this be affected by Family Relationships?
- Could data be affected by Merging Patient Profiles?
- Could data be affected by rebooking/canceling appointments or changing treatments?
- Can this be Created, Updated, Archived/Unarchived or Deleted? (CRUD Test)
- Activity Report?
- Trigger a validation Error?

## Peer Review for Moderate Risk or Higher
- [ ]  Peer Review

## Pass Story on QA Board / Mark Done in Jira/ Mark Scheduled for Release in Linear
- [ ]  LGTM 🚀

**Pull request merged**
