### PR TITLE
[LANG-19] Telehealth Translations (iOS app) 

### PR DESCRIPTION
**Pull request by ivanjiang5628**
## Description
- [Linear Ticket](https://linear.app/jane/issue/LANG-19/translate-telehealth-features)

- Adds French translations for the jitsi ios app (Thanks google translate)

Demo:

https://www.loom.com/share/4b3c2bce34ed48309f7c067a4dea62b9

### General PR Class
👁 = UX / UI improvement

- [ ] requires env configuration to be added in production
- [ ] js package changes<sup>1</sup>
- [ ] more than 200 LOC changed in production files<sup>1</sup>
- [ ] includes a user-facing workflow change to an existing production feature (user muscle memory or pattern recognition will be affected)
- [ ] could prevent access to Jane Video (eg. cors, middleware, changes to auth system)
- [x] affects a widely used component or piece of code
- [ ] I have a doubt - I want the RMT to review this. If possible, please elaborate your concerns in the risk assessment section.

<sup>1</sup> No need to explain these risk factors below

### Release Risk Assessment
Medium risk.
This PR may affect non-French-speaking telehealth users.

### Demo Notes
https://www.loom.com/share/4b3c2bce34ed48309f7c067a4dea62b9

## Code Review
Resource: [Dev Team Notion Page](https://www.notion.so/janeapp/Dev-Team-f06c6eb2ccca4066bc63fc1ac1bd2549)
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)

- [x] I clearly explained the WHY behind the work, in the Description above

#### Design
- [x] I added instructions for how to test, in the QA section below
- [x] I added specs for changes, or determined that none were required
- [x] I demoed this to the appropriate person
- [x] I considered both mobile & desktop views, or that wasn't relevant

#### Code
- [x] I committed code with informative git messages
- [x] I wrote readable code, or added comments if it was complex
- [x] I performed a self-review of my own code
- [x] I rebased my branch on the latest `master`

### Steps to Reproduce
1. Go to setting -> general -> Language & Region -> set iPhone/iPad language as "French"
2. Go to the video chat app.
3. All UI should be in French.

### After

### CODE REVIEW

**Comment by JuliaMoniqueRix** [comment]
## Demo / Pre QA Testing

- [x] Confirm French translation working on iPhone
- [x] Confirm working on web app once set in the Video Settings

**Comment by JuliaMoniqueRix** [comment]
@ivanjiang5628 Translations look good now that we got the settings all straightened out. 🤦🏻‍♀️ Ready for Code Review 🚀

**Review by hollandmatt — APPROVED** [review]
Tres bien.

**Comment by jngo-janeapp** [comment]
Before Testing Pre-QA
- [x] CI must be passing
- [x] No conflicts
- [x] No unresolved reviews/changes requested
- [x] No additional changes/pushes from dev since the last round of QA
- [x] Release note is sufficient for [#features](https://janeapp.slack.com/archives/C0KC1395G)
- [x] Read through Notion / Jira story / Linear Issue / Slack Convo / Demo video
- [x] Read through comments

## Developer's Recommended Test Plan
- [x] Go to setting -> general -> Language & Region -> set iPhone/iPad language as "French"
Image from iOS (8)
Image from iOS (7)
Image from iOS (6)
- [x] Go to the video chat app.
- [x] All UI should be in French.
Image from iOS (1)
Image from iOS (2)
Image from iOS (3)
Image from iOS (4)
Image from iOS (5)
Image from iOS


## Additional Thoughts on Testing
- [x] Call works as expected 

## Mobile, Browsers, Jane Desktop
- [x] iPad Mini
- [x] iPhone

## Pass Story on QA Board / Mark Done in Jira/ Mark Scheduled for Release in Linear
- [x]  LGTM

## Portfolio Team label is added to PR
- [x]  Portfolio Team label is added

## Move PR on Roll Out Board
- [x]  Moved from **QA** to **Patch Release Candidate**

**Comment by jngo-janeapp** [comment]
hey @ivanjiang5628 this one looks ✅

**Comment by jngo-janeapp** [comment]
Adding `knock knock` from ioS view and web browser view 

Screen Shot 2021-07-09 at 1 09 38 PM
Screen Shot 2021-07-09 at 1 09 51 PM
Screen Shot 2021-07-09 at 1 16 43 PM
Screen Shot 2021-07-09 at 1 15 55 PM
Screen Shot 2021-07-09 at 1 18 37 PM
Screen Shot 2021-07-09 at 1 18 53 PM
Screen Shot 2021-07-09 at 1 20 12 PM
Image from iOS (6)
Image from iOS (7)
Image from iOS (8)
Image from iOS (9)
Image from iOS (10)

**Pull request merged**
