### PR TITLE
Jane Online Appointments Activity Log [Web app]

### PR DESCRIPTION
**Pull request by ivanjiang5628**
## Description
In response to Apple's rejection of our most recent Waiting Room build, we decided to remove all third-party analytics tooling (Amplitude & Mamoto) from our video chat app and send logs to Jane directly. This PR is for web app only

[Jane PR](https://github.com/janeapp/jane/pull/9280)

In this PR:
- Add `JaneHandler` to send analytics events to jane directly.
- Remove `AmplitudeHandler` & `MamotoHandler`
- Update the `waiting room` analytics events to make them more readable in datadog

### General PR Class
🌟 = New Feature (Adds Functionality)

### Dependencies / ENV
N/A

- [ ] requires env configuration to be added in production
- [x] js package changes<sup>1</sup>
- [x] more than 200 LOC changed in production files<sup>1</sup>
- [ ] includes a user-facing workflow change to an existing production feature (user muscle memory or pattern recognition will be affected)
- [ ] could prevent access to Jane Video (eg. cors, middleware, changes to auth system)
- [ ] affects a widely used component or piece of code
- [ ] I have a doubt - I want the RMT to review this. If possible, please elaborate your concerns in the risk assessment section.

<sup>1</sup> No need to explain these risk factors below

### Release Risk Assessment
Medium, we remove amplitude-js from package.json

### Demo Notes
image

## Code Review
Resource: [Dev Team Notion Page](https://www.notion.so/janeapp/Dev-Team-f06c6eb2ccca4066bc63fc1ac1bd2549)
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)

### Steps to Reproduce
1. Create an online appointment.
3. Join the call -> hang up the call.
4. Go to [datadog](https://app.datadoghq.com/logs?query=&cols=host%2Cservice%2C%40network.client.ip&index=%2A&messageDisplay=inline&stream_sort=desc)
5. Click on "Views" -> select "Online appointment activity logs" -> replace the `@params.id:*` with `@params.id:"your room name"`

### Fixed / Expected Behaviour
Data dog should show the activity logs of the call.

### After

### CODE REVIEW

**Comment by JuliaMoniqueRix** [comment]
So good @ivanjiang5628! Nice work! Ready for Code Review!

https://app.datadoghq.com/logs?query=%40params.id%3A%2A%20%40rails.resource%3Avideo_chat_sessions%23event%20%40http.status_code%3A200&cols=%40http.useragent_details.browser.family%2C%40params.participant_type%2C%40params.participant_id%2C%40http.useragent_details.os.family%2C%40params.name&index=%2A&integration_id=&integration_short_name=&messageDisplay=inline&saved_view=481094&stream_sort=desc&viz=stream&from_ts=1628284241477&to_ts=1628889041477&live=true

**Review by hollandmatt — APPROVED** [review]
Looks good!

**Comment by CasTodesco** [comment]
test plan done in Jane PR: https://github.com/janeapp/jane/pull/9280

**Comment by CasTodesco** [comment]
@brandon-janeapp could we have one more review from you please before passing this

**Comment by CasTodesco** [comment]
test plan done in Jane PR: https://github.com/janeapp/jane/pull/9280

**Review by brandon-janeapp — APPROVED** [review]

**Comment by CasTodesco** [comment]
testing done in Jane PR: https://github.com/janeapp/jane/pull/9280

**Pull request merged**
