### PR TITLE
Fix keyboard no longer covers message board and input (ios) 

### PR DESCRIPTION
**Pull request by ivanjiang5628**
## Description
- Fix a bug that the iOS system keyboard covers the chat message board and input

Demo Video:
https://www.loom.com/share/f21de4ba993a4c4b93af54d91eb7fe91

### General PR Class
🐛 = Bug Fix (Fixes an Issue)

### Dependencies / ENV

- [ ] requires env configuration to be added in production
- [ ] js package changes<sup>1</sup>
- [ ] more than 200 LOC changed in production files<sup>1</sup>
- [ ] includes a user-facing workflow change to an existing production feature (user muscle memory or pattern recognition will be affected)
- [ ] could prevent access to Jane Video (eg. cors, middleware, changes to auth system)
- [ ] affects a widely used component or piece of code
- [ ] I have a doubt - I want the RMT to review this. If possible, please elaborate your concerns in the risk assessment section.

<sup>1</sup> No need to explain these risk factors below

### Release Risk Assessment
Should be low.

## Code Review
Resource: [Dev Team Notion Page](https://www.notion.so/janeapp/Dev-Team-f06c6eb2ccca4066bc63fc1ac1bd2549)
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)

- [x] I clearly explained the WHY behind the work, in the Description above

#### Design
- [x] I added instructions for how to test, in the QA section below
- [x] I added specs for changes, or determined that none were required
- [x] I demoed this to the appropriate person
- [x] I considered both mobile & desktop views, or that wasn't relevant

#### Code
- [x] I committed code with informative git messages
- [x] I wrote readable code, or added comments if it was complex
- [x] I performed a self-review of my own code
- [x] I rebased my branch on the latest `master`

### Steps to Reproduce
1. Join the call on an iOS device
2. Open the chat window (Chat between staff member and patient)
3. Open the soft keyboard in the chat window.
4. The soft keyboard will not overlaps chat and chat input 

### After

### CODE REVIEW

**Comment by JuliaMoniqueRix** [comment]
## Demo / Pre QA Testing

- [x] Chat between staff member and patient
- [x] Confirm that the keyboard does not get blocked on iOS
- [x] Confirm messages are sent successfully in both directions

LGTM @ivanjiang5628 🚀

**Review by hollandmatt — APPROVED** [review]
⌨️

**Comment by jngo-janeapp** [comment]
Before Testing Pre-QA
- [x] CI must be passing
- [x] No conflicts
- [x] No unresolved reviews/changes requested
- [x] No additional changes/pushes from dev since the last round of QA
- [x] Release note is sufficient for [#features](https://janeapp.slack.com/archives/C0KC1395G)
- [x] Read through Notion / Jira story / Linear Issue / Slack Convo / Demo video
- [x] Read through comments

## Developer's Recommended Test Plan
- [x] Ensure waiting area feature flag is enabled
- [x] Keyboard works as expected 
Image from iOS (1)
Image from iOS (2)
Image from iOS (3)
Image from iOS (4)
Image from iOS (5)
Image from iOS (6)


## Additional Thoughts on Testing
- [x] All buttons work as expected 

## Mobile, Browsers, Jane Desktop
- [x] Google Chrome
- [x] Safari
- [x] Firefox

## Pass Story on QA Board / Mark Done in Jira/ Mark Scheduled for Release in Linear
- [x]  LGTM

## Portfolio Team label is added to PR
- [x]  Portfolio Team label is added

## Move PR on Roll Out Board
- [x]  Moved from **QA** to **Patch Release Candidate**

**Comment by jngo-janeapp** [comment]
hey @ivanjiang5628 this PR looks ready and good to go ✅  

I did notice when on my mobile app and closing the app and not leaving the call i remained in the call from the practitioners point of view; here is a screenshot of what I was seeing from the practitioner view. 

Screen Shot 2021-07-08 at 1 53 13 PM

**Pull request merged**
