### PR TITLE
[IMPT-46] Update Crashlytics

### PR DESCRIPTION
**Pull request by ivanjiang5628**
## Description
- [Jira Ticket](https://janeapp.atlassian.net/browse/TEL-293)

Because The Fabric SDK is now deprecated and will not continue reporting the app's crashes.
I removed the Fabric SDK and added the latest Firebase Crashlytics SDK to the app by following the [guides.](https://firebase.google.com/docs/crashlytics/get-started?platform=ios&authuser=0#add-sdk)

image

### General PR Class
🐛 = Bug Fix (Fixes an Issue)

### Dependencies / ENV

- [ ] requires env configuration to be added in production
- [ ] js package changes<sup>1</sup>
- [ ] more than 200 LOC changed in production files<sup>1</sup>
- [ ] includes a user-facing workflow change to an existing production feature (user muscle memory or pattern recognition will be affected)
- [ ] could prevent access to Jane Video (eg. cors, middleware, changes to auth system)
- [ ] affects a widely used component or piece of code
- [ ] I have a doubt - I want the RMT to review this. If possible, please elaborate your concerns in the risk assessment section.

<sup>1</sup> No need to explain these risk factors below

### Release Risk Assessment
Low

## Code Review
Resource: [Dev Team Notion Page](https://www.notion.so/janeapp/Dev-Team-f06c6eb2ccca4066bc63fc1ac1bd2549)
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)

- [x] I clearly explained the WHY behind the work, in the Description above

#### Design
- [ ] I added instructions for how to test, in the QA section below
- [ ] I added specs for changes, or determined that none were required
- [x] I demoed this to the appropriate person
- [x] I considered both mobile & desktop views, or that wasn't relevant

#### Code
- [x] I committed code with informative git messages
- [x] I wrote readable code, or added comments if it was complex
- [x] I performed a self-review of my own code
- [x] I rebased my branch on the latest `master`

### CODE REVIEW

**Review by gerbus — APPROVED** [review]
Tough to code review these files, but looks about right to me. I don't see a QA section in your PR write-up, but I imagine you did some developer QA? In `/janeapp/jane` we're starting to move towards documenting the developer QA in that section. I'm happy if you just confirm that you tested this, but for the future something to consider.

**Comment by ivanjiang5628** [comment]
> Tough to code review these files, but looks about right to me. I don't see a QA section in your PR write-up, but I imagine you did some developer QA? In `/janeapp/jane` we're starting to move towards documenting the developer QA in that section. I'm happy if you just confirm that you tested this, but for the future something to consider.

👍 Hi, Chris Yes I did some developer QA I think it would be great to have the developer QA section in this repo!

**Comment by gerbus** [comment]
> > Tough to code review these files, but looks about right to me. I don't see a QA section in your PR write-up, but I imagine you did some developer QA? In `/janeapp/jane` we're starting to move towards documenting the developer QA in that section. I'm happy if you just confirm that you tested this, but for the future something to consider.
> 
> 👍 Hi, Chris Yes I did some developer QA I think it would be great to have the developer QA section in this repo!

Great! Once the PR template is updated in janeapp/jane I'll try to remember to port the relevant stuff over here too 👍

**Comment by clem-jane** [comment]
@jngo-janeapp could we get your help to QA this?

**Comment by jngo-janeapp** [comment]
## Before Testing
- [ ] CI must be passing
- [ ] No conflicts
- [ ] No unresolved reviews/changes requested
- [ ] No additional changes/pushes from dev since the last round of QA
- [ ] Release note is sufficient for [#features](https://janeapp.slack.com/archives/C0KC1395G)
- [ ] Read through Notion / Jira story / Linear Issue / Slack Convo / Demo video
- [ ] Read through comments

## Developer's Recommended Test Plan
- [ ] TBD

## Additional Thoughts on Testing
- [ ] TBD

## Mobile, Browsers, Jane Desktop
- [ ] Google Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] iPad Mini
- [ ] iPhone

## Regression Testing / Exploratory
(Consider related areas or areas where data persists Ie. Chart Templates/Intake Forms, Chart Entries/Export to PDF, Reports / Export to CSV/xls, Payment / Receipts / Superbill(US))
- Can you export a PDF from this area/function?
- Can this functionality be reused somewhere else in Jane? Or does it share components with other areas in Jane. (Canadian & US Insurance)
- Does this area have an inverse setting? Enabled/Disabled, Beta Feature Flag
- When testing emails: Have you tested both with an email on file and with no email on file, manually triggered emails (Welcome, Password Reset, Intake Form, Upcoming Appointments) and automated emails: Thanks for Booking, Cancelations, Reminders, Surveys, Telehealth, R&R, and RVR. Also, have you tried to trigger Family Relationship emails?
- Does this area have multiple setting types? Ie. Intake Forms, Permissions/Privacy, User types
- Does this correspond to an area in Online Booking? (Booking an appointment, Entering a credit card and paying for an appointment)
- Is this related to Payment Methods? Jane Payments: Stripe, Payfirma, Square Terminal, Cash, Gift Cards, Credit Memos, Account Credit, Packages
- Could this be affected by Family Relationships?
- Could data be affected by Merging Patient Profiles?
- Could data be affected by rebooking/canceling appointments or changing treatments?
- Can this be Created, Viewed, Updated, Archived/Unarchived or Deleted? (CRUD Test)
- Activity Report?
- Trigger a validation Error?
- Should we test different Staff Member Permissions and SU?
- Does this change functionality where existing data or settings may be affected? Might we need to create existing data/settings and then deploy the PR to the sandbox to see how it behaves to replicate how a real-life account might experience the change?

## Pass Story on QA Board / Mark Done in Jira/ Mark Scheduled for Release in Linear
- [ ] LGTM

## Move PR on Roll Out Board
- [ ] Moved from **QA** to **Patch Release Candidate**

**Comment by jngo-janeapp** [comment]
> @jngo-janeapp could we get your help to QA this?

Hey @clem-jane don't think there is much for me to QA here as its been developer QA'd as per the notes above. I'll speak with Ivan when he's back to see if there is anything I can test on my end @ivanjiang5628 thanks!

**Pull request merged**
