### PR TITLE
[SCH-265] Add bugsnag to the iOS app

### PR DESCRIPTION
**Pull request by ivanjiang5628**
## Description
- [Linear Ticket](https://linear.app/jane/issue/SCH-265/telehealth-add-bugsnag-to-the-ios-app)

- Add bugsnag to the jitsi iOS app
- see bugsnag docs: https://docs.bugsnag.com/platforms/react-native/react-native/manual-setup/

### General PR Class
🌟 = New Feature (Adds Functionality)
☕️ = JS Dependency Changes

### Release Note
Add bugsnag to the jitsi iOS app

### Dependencies / ENV
 "@bugsnag/react-native": "^7.9.2",
 "@bugsnag/source-maps": "^2.0.0",

- [ ] requires env configuration to be added in production
- [ ] js package changes<sup>1</sup>
- [ ] more than 200 LOC changed in production files<sup>1</sup>
- [ ] includes a user-facing workflow change to an existing production feature (user muscle memory or pattern recognition will be affected)
- [ ] could prevent access to Jane Video (eg. cors, middleware, changes to auth system)
- [ ] affects a widely used component or piece of code
- [ ] I have a doubt - I want the RMT to review this. If possible, please elaborate your concerns in the risk assessment section.

<sup>1</sup> No need to explain these risk factors below

### Release Risk Assessment
Low

## Code Review
Resource: [Dev Team Notion Page](https://www.notion.so/janeapp/Dev-Team-f06c6eb2ccca4066bc63fc1ac1bd2549)
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)

- [x] I clearly explained the WHY behind the work, in the Description above

#### Design
- [x] I added instructions for how to test, in the QA section below
- [x] I added specs for changes, or determined that none were required
- [ ] I demoed this to the appropriate person
- [x] I considered both mobile & desktop views, or that wasn't relevant

#### Code
- [x] I committed code with informative git messages
- [x] I wrote readable code, or added comments if it was complex
- [x] I performed a self-review of my own code
- [x] I rebased my branch on the latest `master`

### Steps to Reproduce
this PR contains some behind the scenes changes >  smoke test only

### Fixed / Expected Behaviour
Manually threw an error inside the app & I could see the report on bugsnag.
https://app.bugsnag.com/jane-clinic-management/jitsi-rn-client-1/errors/606d297c36789600071b50ac?filters[event.since][0]=30d&filters[error.status][0]=open

image

### CODE REVIEW

**Review by hollandmatt — APPROVED** [review]
Looks good! My one concern was having the API key checked in, but it seems like we're doing that already for the webapps (I suppose it's distributed in the JS so it can't really be "secret")

**Comment by ivanjiang5628** [comment]
> Looks good! My one concern was having the API key checked in, but it seems like we're doing that already for the webapps (I suppose it's distributed in the JS so it can't really be "secret")

good catch! I'll remove the API key from this PR.

**Comment by jngo-janeapp** [comment]
Chatted with @ivanjiang5628 and we're moving this PR along ✅

**Comment by ivanjiang5628** [comment]
Closing PR as we decided not to add bugsnag to the app

**Pull request closed without merging**
