### PR TITLE
[TEL-279] Telehealth waiting area/ practitioner tool web

### PR DESCRIPTION
**Pull request by ivanjiang5628**
## Description
- [Jira Ticket](https://janeapp.atlassian.net/browse/TEL-279)
- [Jane Admin PR](https://github.com/janeapp/jane/pull/5912)
- [Notion](https://www.notion.so/janeapp/Telehealth-Practitioner-Tools-Waiting-Room-16330e2807294cefb8002b87a17ead3f)

- Added `jane-waiting-area` feature components/reducer/actions. (based on jitsi version 4627's prejoin feature.)
- new fonts and CSS updates.
- Added the `SocketConnection` component for the `react-native` app to connect the jane socket.io server.
- Added the `Socket` component for socket.io connection.

- [ ] requires env configuration to be added in production
- [x] js package changes<sup>1</sup>
- [x] more than 200 LOC changed in production files<sup>1</sup>
- [x] includes a user-facing workflow change to an existing production feature (user muscle memory or pattern recognition will be affected)
- [x] could prevent access to Jane Video (eg. cors, middleware, changes to auth system)
- [ ] affects a widely used component or piece of code
- [ ] I have a doubt - I want the RMT to review this. If possible, please elaborate your concerns in the risk assessment section.

<sup>1</sup> No need to explain these risk factors below

🌟 = New Feature (Adds Functionality)
☕️ = JS Dependency Changes

### Demo Notes

Loom video :

https://www.loom.com/share/753bda1e80f64712bab0d386ab12b7fa

## Code Review
Resource: [Dev Team Notion Page](https://www.notion.so/janeapp/Dev-Team-f06c6eb2ccca4066bc63fc1ac1bd2549)
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)

- [x] I clearly explained the WHY behind the work, in the Description above

#### Design
- [x] I added instructions for how to test, in the QA section below
- [ ] I added tests for changes, or determined that none were required
- [ ] I demoed this to the appropriate person
- [x] I considered both mobile & desktop views, or that wasn't relevant

#### Code
- [x] I committed code with informative git messages
- [x] I wrote readable code, or added comments if it was complex
- [x] I performed a self-review of my own code
- [x] I rebased my branch on the latest `master`
- [x] I confirmed that all CircleCI tests are passing
- [ ] I didn't add new npm packages, or else I made damn sure the `yarn.lock` changes are safe for existing production packages

### Steps to Reproduce
Create an online appointment in jane admin app -> go to the video chat -> You will see the waiting area page.

### Fixed / Expected Behaviour
From the waiting area page.
-> When the patient opens the video chat app, the practitioner-side video chat app will show the `Admit client` button.

-> If the practitioner clicks on the admit button, the practitioner joins the call the patient-side video chat app will show the `begin` button.

-> the patient can click the begin button to jump on the call.

-> When both participants are on the waiting area page:
- if the practitioner leaves the waiting area -> the patient-side will not allow the patient to join the call and the `begin` button will be removed from the dialog box.
- if the patient leaves the waiting area -> the practitioner-side will not allow the practitioner to join the call and the `Admit Client` button will be removed from the dialog box.

### Jitsi backend update
N/A 

### After

### CODE REVIEW

**Comment by gerbus** [comment]
Just a heads up that there are some linter errors

**Comment by ivanjiang5628** [comment]
> Just a heads up that there are some linter errors

**Comment by ivanjiang5628** [comment]
> Just a heads up that there are some linter errors

Oh yes, I will fix the linter erros later.

**Review by gerbus — COMMENTED** [review]
I took a brief look through some sample of files and nothing jumped out at me really. However this is a huge PR with more than 5000 LOC changed (usually the release management team flags PRs bigger than 200 LOC changed as medium risk). Ideally for a feature this big, it's broken up into multiple PRs. I'm not sure if this feature could have been rolled out in stages, but even just for code-review ease, it's nice to look at smaller PRs (better chance of catching stuff).

**Comment by ivanjiang5628** [comment]
> I took a brief look through some sample of files and nothing jumped out at me really. However this is a huge PR with more than 5000 LOC changed (usually the release management team flags PRs bigger than 200 LOC changed as medium risk). Ideally for a feature this big, it's broken up into multiple PRs. I'm not sure if this feature could have been rolled out in stages, but even just for code-review ease, it's nice to look at smaller PRs (better chance of catching stuff).

Agree👍  I will split this PR

**Comment by ivanjiang5628** [comment]
close this PR because I split it into 3PRs: [TEL-290](https://github.com/janeapp/video-chat/pull/25), [TEL-289](https://github.com/janeapp/video-chat/pull/24), ,[TEL-282](https://github.com/janeapp/video-chat/pull/17),

**Pull request closed without merging**
