### PR TITLE
[Fix] Video not displaying even when turned on

### PR DESCRIPTION
**Pull request by ivanjiang5628**
## Description
[notion](https://www.notion.so/janeapp/Video-not-displaying-even-when-turned-on-c9a988f2d5df46888a7a02a834cfc40a)

### Issue:
Some participant will have their video on (can see themselves) but to the other participant, it will appear that their video is either off (shows initials) or is all black. (After the 5076 upgrade)

### Cause:
Jitsi updated their `lib-jitsi-meet` library code in August for the "layer suspension" feature. This update caused the app to stop encoding the sender's video track occasionally(can not get the sender video height properly.) if the app doesn't have the layerSuspension config option enabled.

more info: https://github.com/jitsi/lib-jitsi-meet/issues/1333#issuecomment-708513033

### Fix:
Set sender video constraint to 720 when user joining the conference to avoid the `null` sender video height issue.

### Note:
Jitsi included a fix in release `2.0.5390` (21-01-12)
https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-WEB.md

We may need to remove this fix when we upgrade the app to 5390.

### General PR Class
🐛 = Bug Fix (Fixes an Issue)

- [ ] requires env configuration to be added in production
- [ ] js package changes<sup>1</sup>
- [ ] more than 200 LOC changed in production files<sup>1</sup>
- [ ] includes a user-facing workflow change to an existing production feature (user muscle memory or pattern recognition will be affected)
- [ ] could prevent access to Jane Video (eg. cors, middleware, changes to auth system)
- [ ] affects a widely used component or piece of code
- [ ] I have a doubt - I want the RMT to review this. If possible, please elaborate your concerns in the risk assessment section.

<sup>1</sup> No need to explain these risk factors below

### Release Risk Assessment
Low 

### Demo Notes
it is a behind-the-scenes fix, Can not be demoed.

## Code Review
Resource: [Dev Team Notion Page](https://www.notion.so/janeapp/Dev-Team-f06c6eb2ccca4066bc63fc1ac1bd2549)
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)

- [x] I clearly explained the WHY behind the work, in the Description above

#### Design
- [x] I added instructions for how to test, in the QA section below
- [x] I added specs for changes, or determined that none were required
- [ ] I demoed this to the appropriate person
- [x] I considered both mobile & desktop views, or that wasn't relevant

#### Code
- [x] I committed code with informative git messages
- [x] I wrote readable code, or added comments if it was complex
- [x] I performed a self-review of my own code
- [x] I rebased my branch on the latest `master`

### Fixed / Expected Behaviour
it is a behind-the-scenes fix, Smoke test on the video chat web app.

### CODE REVIEW

**Review by gerbus — APPROVED** [review]
Yeah this seems to make sense. I scanned through the Github issue you linked, nice find.

I guess one thing I don't really like is that if there's an error setting this constraint, we have no fallback. But I guess we'd see these logger errors somewhere? @ivanjiang5628 do you know where these logger errors go for Jane?

**Comment by gerbus** [comment]
You have a build error to sort out still FYI:
Screen Shot 2021-01-29 at 10 39 42

**Comment by ivanjiang5628** [comment]
> Yeah this seems to make sense. I scanned through the Github issue you linked, nice find.
> 
> I guess one thing I don't really like is that if there's an error setting this constraint, we have no fallback. But I guess we'd see these logger errors somewhere? @ivanjiang5628 do you know where these logger errors go for Jane?
if the `conference.setSenderVideoConstraint` function thorws a error Bugsnag will catch it.

**Comment by jngo-janeapp** [comment]
Smoke Test: 
- [x] User can see admin booked
- [x] User can see patient booked 
- [x] User can begin online video appointment 
- [x] User can see patient begin test my setup 
- [x] User can toggle video on/off when in test my setup 
- [x] User can begin video session from patient side 
- [x] User can toggle video on/off
- [x] User can see all buttons work as expected 
- [x] User can complete review after end session 
Patient__103_-_Demo_Clinic_-_Jane_and_Slack___ivan___Jane_and_My_Account___Demo_Clinic

**Pull request merged**
