### PR TITLE
[PAT-914] Remove Google Analytics from the Jitsi web app

### PR DESCRIPTION
**Pull request by ivanjiang5628**
## Description
- [Linear Ticket](https://linear.app/jane/issue/PAT-914/remove-google-analytics-from-the-jitsi-web-app)

- Remove GoogleAnalyticsHandler from global analytics handler

### Release Risk Assessment
Low Risk

### Steps to Reproduce
Just need a smoke test

### After

### CODE REVIEW

**Review by brendonion — APPROVED** [review]

**Comment by brendonion** [comment]
Should we just delete the code?

**Review by bitghost2m — APPROVED** [review]

**Review by tom-roper — APPROVED** [review]

**Review by gregmoreno — COMMENTED** [review]
@ivanjiang5628 Why commenting them out and not completely removing them?

**Comment by ivanjiang5628** [comment]
> @ivanjiang5628 Why commenting them out and not completely removing them?

As this file originally came from Jitsi, if we want to upgrade the app (rebase upstream), deleting it may cause problems.(i.e. it will be added back after rebasing upstream)
Perhaps it would be ideal to comment them out

**Comment by kaeramirez** [comment]
## Test Plan

- [x] Quick smoke test of Jitsi telehealth (joining, functionality, etc.)

## Browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Android Chrome

## Pass PR in GitHub / Mark Scheduled for Release in Linear

- [x]  Mark as "Ready for Release"

**Pull request merged**
