### PR TITLE
[SCH-317] Upgrade iOS app to use Jitsi 2.0.5076

### PR DESCRIPTION
**Pull request by ivanjiang5628**
## Description
- [Linear Ticket](https://linear.app/jane/issue/SCH-317/upgrade-ios-app-to-use-jitsi-205076)

  - Rebase the our react-native prod branch onto upstream jitsi 5076 branch to upgrade the ios app from 4378 to 5076.
  - Resolve merge conflicts
  - Fix eslint & flow errors to pass CI
  - Reconfigure the waiting area directory for native & web components to pass CI.
  - Fix the image not displaying correctly in iOS 14 issue.

### General PR Class
🌦 = Env Changes
☕️ = JS Dependency Changes

- [ ] requires env configuration to be added in production
- [x] js package changes<sup>1</sup>
- [x] more than 200 LOC changed in production files<sup>1</sup>
- [ ] includes a user-facing workflow change to an existing production feature (user muscle memory or pattern recognition will be affected)
- [ ] could prevent access to Jane Video (eg. cors, middleware, changes to auth system)
- [ ] affects a widely used component or piece of code
- [ ] I have a doubt - I want the RMT to review this. If possible, please elaborate your concerns in the risk assessment section.

<sup>1</sup> No need to explain these risk factors below

### Release Risk Assessment
Over 60000 lines changes...So it is a high-risk PR.

## Code Review
Resource: [Dev Team Notion Page](https://www.notion.so/janeapp/Dev-Team-f06c6eb2ccca4066bc63fc1ac1bd2549)
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)

- [ ] I clearly explained the WHY behind the work, in the Description above

#### Design
- [ ] I added instructions for how to test, in the QA section below
- [ ] I added specs for changes, or determined that none were required
- [ ] I demoed this to the appropriate person
- [ ] I considered both mobile & desktop views, or that wasn't relevant

#### Code
- [ ] I committed code with informative git messages
- [ ] I wrote readable code, or added comments if it was complex
- [ ] I performed a self-review of my own code
- [ ] I rebased my branch on the latest `master`

### Steps to Reproduce
1. Download V1.4.0 from TestFlight. 
2. Please ensure everything works properly (No changes to functionality with this upgrade).

### After

### CODE REVIEW

**Comment by JuliaMoniqueRix** [comment]
## Demo / Pre QA Testing

- [x] Confirm patient and staff member can connect as expected
- [x] Confirm feature settings working as expected

**Comment by JuliaMoniqueRix** [comment]
Looking good @ivanjiang5628! Ready for Code Review. 🚀

**Review by hollandmatt — APPROVED** [review]
Discussed with Ivan on Slack - this PR isn't really reviewable due to it's size, but the changes are all from the upstream repo (i.e. not Jane changes). So long as we have a comprehensive QA for this one, should be good to go.

**Comment by JuliaMoniqueRix** [comment]
@ivanjiang5628 This looks ready for QA.  The only problem I stumbled upon after our recent settings updates was the one you documented which jitsi appears to know about.

https://github.com/jitsi/jitsi-meet/issues/4176#issuecomment-724842367

**Comment by jngo-janeapp** [comment]
This PR looks really good; didn't see any regression when testing through a list of PRs (since this one is just a smoke test) 
Chatted with @ivanjiang5628 and we're good to go ✅

**Pull request merged**
