### PR TITLE
[SCH-340] Video chat web app sends "left waiting room" signal twice to Jane when user hangs up the call

### PR DESCRIPTION
**Pull request by ivanjiang5628**
## Description
- [Linear](https://linear.app/jane/issue/SCH-340/video-chat-app-sends-left-waiting-room-signal-twice-to-jane-when-users)

### Issue: 
The web app sends the "left waiting room" signal multiple times (twice) to the `/video_chat_sessions/update_participant_status` endpoint when a user hangs up the call. 

### Cause:
We want the web app to send the "left" waiting room signal to Jane after a user clicks the `hangup` button or closes the browser window directly. Although the `hangup` handler function will also execute the `window.close()` to close the browser window and this might trigger the `window.beforeunload` & `window.unload` callbacks. However, I noticed that sometimes those callbacks are not guaranteed to be executed. So I have to place the sending `left` signal action in those callbacks and the `hangup` function to ensure Jane can receive the signal and this results in sometimes the app repeatedly firing the request in the callbacks and the hangup function.

### Solution:
In this PR:
- Use the `window.APP.waitingArea.status` global variable as a flag to indicate the status of the waiting area component.
- Check the `window.APP.waitingArea.status` flag before sending the "left" signal, only allow to send if the waiting room status is `initialized` in order to prevent firing the request repeatedly.
- Rewrite the waiting area `UpdateParticipantStatus` function for better error handling.
- Remove unused code.

### General PR Class
🐛 = Bug Fix (Fixes an Issue)

### Dependencies / ENV

- [ ] requires env configuration to be added in production
- [ ] js package changes<sup>1</sup>
- [ ] more than 200 LOC changed in production files<sup>1</sup>
- [ ] includes a user-facing workflow change to an existing production feature (user muscle memory or pattern recognition will be affected)
- [ ] could prevent access to Jane Video (eg. cors, middleware, changes to auth system)
- [ ] affects a widely used component or piece of code
- [ ] I have a doubt - I want the RMT to review this. If possible, please elaborate your concerns in the risk assessment section.

<sup>1</sup> No need to explain these risk factors below

### Release Risk Assessment
Low risk

### Demo Notes
https://www.loom.com/share/b8e55ad51b5e4fd68519c8757dc14281

## Code Review
Resource: [Dev Team Notion Page](https://www.notion.so/janeapp/Dev-Team-f06c6eb2ccca4066bc63fc1ac1bd2549)
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)

- [x] I clearly explained the WHY behind the work, in the Description above

#### Design
- [x] I added instructions for how to test, in the QA section below
- [x] I added specs for changes, or determined that none were required
- [ ] I demoed this to the appropriate person
- [x] I considered both mobile & desktop views, or that wasn't relevant

#### Code
- [x] I committed code with informative git messages
- [x] I wrote readable code, or added comments if it was complex
- [x] I performed a self-review of my own code
- [x] I rebased my branch on the latest `master`

### Steps to Reproduce
1. Enabled the `waiting area` beta feature.
2. Create an online appointment
3. Join the call
4. Click on the `Hangup` Button.
5. Go to datadog, please use this [Link](https://app.datadoghq.com/logs/livetail?agg_m=count&agg_q=&agg_t=count&cols=host%2Cservice%2C%40params.info.status%2C%40network.client.ip&from_ts=0&index=&live=true&messageDisplay=inline&query=%40controller%3Avideo_chat_sessions+%40action%3Aupdate_participant_status+%40http.host%3As14.jane.qa&sort_m=&sort_t=&stream_sort=desc&to_ts=-1&top_n=&top_o=&viz=stream) to monitor the `update_participant_status` endpoint in real-time.(if testing on S14 sandbox)
6. There should be only one POST request with 'left' params after clicking the `Hangup` button

Please also ensure the `waiting area` feature works properly.

### Fixed / Expected Behaviour
When users hang up the call or close the browser window, the web app should send the "left" signal to Jane only once.

### Before
on Datadog:
ae6dae83-04dd-4c5c-b56a-26664a83cd17

### After
on Datadog:
image

### CODE REVIEW

**Review by hollandmatt — APPROVED** [review]
Looks good!

**Comment by jngo-janeapp** [comment]
Before Testing QA Tuesday June 15th 
- [x] CI must be passing
- [x] No conflicts
- [x] No unresolved reviews/changes requested
- [x] No additional changes/pushes from dev since the last round of QA
- [x] Release note is sufficient for [#features](https://janeapp.slack.com/archives/C0KC1395G)
- [x] Read through Notion / Jira story / Linear Issue / Slack Convo / Demo video
- [x] Read through comments

## Developer's Recommended Test Plan
- [ ] Enabled the waiting area beta feature.
- [ ] Create an online appointment
- [ ] Join the call
- [ ] Click on the Hangup Button.
- [ ] Go to datadog, please use this Link to monitor the update_participant_status endpoint in real-time.(if testing on S14 sandbox)
- [ ] There should be only one POST request with 'left' params after clicking the Hangup button
- [ ] Please also ensure the waiting area feature works properly.

## Additional Thoughts on Testing
- [ ] TBD

## Mobile, Browsers, Jane Desktop
- [ ] Google Chrome
- [ ] Firefox
- [ ] Safari
- [ ] iPhone


## Pass Story on QA Board / Mark Done in Jira/ Mark Scheduled for Release in Linear
- [ ] LGTM

## Portfolio Team label is added to PR
- [x] Portfolio Team label is added

## Move PR on Roll Out Board
- [ ] Moved from **QA** to **Patch Release Candidate**

**Comment by jngo-janeapp** [comment]
Before Testing QA Tuesday June 15th 
- [x] CI must be passing
- [x] No conflicts
- [x] No unresolved reviews/changes requested
- [x] No additional changes/pushes from dev since the last round of QA
- [x] Release note is sufficient for [#features](https://janeapp.slack.com/archives/C0KC1395G)
- [x] Read through Notion / Jira story / Linear Issue / Slack Convo / Demo video
- [x] Read through comments

## Developer's Recommended Test Plan
- [x] Enabled the waiting area beta feature.
Screen Shot 2021-06-16 at 8 10 26 AM
- [x] Create an online appointment
Screen Shot 2021-06-16 at 8 11 33 AM
Screen Shot 2021-06-16 at 8 12 08 AM
- [x] Join the call
Screen Shot 2021-06-16 at 8 12 47 AM
Screen Shot 2021-06-16 at 8 13 20 AM
- [x] Click on the Hangup Button.
Screen Shot 2021-06-16 at 8 14 08 AM
- [ ] Go to datadog, please use this Link to monitor the update_participant_status endpoint in real-time.(if testing on S14 sandbox)
- [ ] There should be only one POST request with 'left' params after clicking the Hangup button
- [ ] Please also ensure the waiting area feature works properly.

## Additional Thoughts on Testing
- [x] Don't have waiting era beta feature enabled and follow steps above 
Screen Shot 2021-06-16 at 8 01 47 AM
Screen Shot 2021-06-16 at 8 06 20 AM

Screen Shot 2021-06-16 at 8 07 06 AM
Screen Shot 2021-06-16 at 8 08 04 AM

## Mobile, Browsers, Jane Desktop
- [x] Google Chrome
- [x] Firefox
- [x] Safari
- [x] iPhone


## Pass Story on QA Board / Mark Done in Jira/ Mark Scheduled for Release in Linear
- [ ] LGTM

## Portfolio Team label is added to PR
- [x] Portfolio Team label is added

## Move PR on Roll Out Board
- [ ] Moved from **QA** to **Patch Release Candidate**

**Comment by ivanjiang5628** [comment]
Jimmy & Kelvin found that the video chat app occasionally fails to send a 'left' signal to Jane when the user closes the browser window directly, the issue is caused by this PR, I will update the PR and we may need to do another round of QA. Thanks @jngo-janeapp @Kmubere

**Pull request merged**
