### PR TITLE
Upgrade video chat web app to use jitsi 2.0.6433

### PR DESCRIPTION
**Pull request by ivanjiang5628**
## Description
- [Linear](https://linear.app/jane/issue/SCH-683/upgrade-web-app-and-ios-app-to-use-jitsi-206433)

In this PR:

- Rebase master branch onto Jitsi 6433 to upgrade our video chat Web app.
- Stop instantiating transport objects for RN webview page to prevent web view pages from constantly sending Postis(Post message) events to the ios app in the waiting room [Commit](https://github.com/janeapp/video-chat/pull/103/commits/99296a328066b3910aa27d693aedede80836e29a)
- Fix lint & flow errors.

We also want to merge the "ios-app-2.0.6433-upgrade" branch into this branch so that in the future we don't have to maintain two branches.

### Dependencies / ENV

- [ ] requires env configuration to be added in production
- [x] js package changes<sup>1</sup>
- [x] more than 200 LOC changed in production files<sup>1</sup>
- [ ] includes a user-facing workflow change to an existing production feature (user muscle memory or pattern recognition will be affected)
- [ ] could prevent access to Jane Video (eg. cors, middleware, changes to auth system)
- [x] affects a widely used component or piece of code
- [ ] I have a doubt - I want the RMT to review this. If possible, please elaborate your concerns in the risk assessment section.

<sup>1</sup> No need to explain these risk factors below

### Release Risk Assessment
High risk, as this PR has over 80000 lines of changes

However, since this is an upgrade PR and it has over 1400 commits, I don't think we can really code review every single commit, so I believe we might need more extensive smoke tests to ensure the upgrade is working properly

## Code Review
Resource: [Dev Team Notion Page](https://www.notion.so/janeapp/Dev-Team-f06c6eb2ccca4066bc63fc1ac1bd2549)
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)

### Steps to Reproduce
1. Create online appts on S8 and launch the iOS app
2. Please ensure that the waiting room is working properly
3. Please ensure that all functionality during the call is working properly (screen sharing, text chat and video audio mute/unmute, etc.)
4. Please ensure that the user can see the duration/details of the session in the "Report-> Online appointments" & "Report -> Activity" sections of the Jane admin app.

### After

### CODE REVIEW

**Review by hollandmatt — APPROVED** [review]
Chatted to Ivan, this PR isn't really "reviewable" due to its size, so approving based on that. We will have to be doubly careful while QAing this.

I'll add Greg for a review too.

**Review by gregmoreno — APPROVED** [review]
LGTM

**Comment by CasTodesco** [comment]
## Before Testing

- [ ]  CI must be passing
- [ ]  No conflicts
- [ ]  No unresolved reviews/changes requested
- [ ]  No additional changes/pushes from dev since the last round of QA
- [ ]  Release note is sufficient for [#features](https://janeapp.slack.com/archives/C0KC1395G)
- [ ]  Read through Notion / Linear Issue / Slack Convo / Demo video
- [ ]  Read through comments

## Developer's Recommended Test Plan

(Copy and paste the developer's recommended test plan here and format accordingly)

## Additional Thoughts on Testing
Admin Side:

- [ ] Settings > Treatments & Classes > Create an online treatment
- [ ] Book the online treatment into another practitioners schedule (book this in less than an hour from the time it is now).
- [ ] Click Begin
- [ ] Ensure Jane gives the "You are not authorized to join this call" message with the "Sign in as" button.
- [ ] Sign in as the correct practitioner
- [ ] Resend Email notification for the appointment - ensure this sends.
- [ ] Click Begin

Admin Side Test in Video Chat:
More actions button:
- [ ] Display name
- [ ] Manage Video Quality
- [ ] View full screen
- [ ] Settings
- [ ] Mute everyone
- [ ] Toggle Title View
- [ ] Turn camera on and off to ensure this works
- [ ] Open the chat, type a message
- [ ] Raise/Lower your hand
- [ ] Share Screen
- [ ] Hang up the call

Patient Side:
- [ ] Login as a patient and book an online appointment that is scheduled within the next hour
- [ ] Ensure you get an email notification
- [ ] Login to your account and join the appointment
- [ ] Consent to video call
- [ ] Test the same video call settings

- [ ] Camera
- [ ] Mute/Un mute
- [ ] Chat
- [ ] Test on multiple browsers to make sure this works

Waiting Room:
- [ ] Turn on waiting room beta
- [ ] Join the session as a practitioner and admit button should be grey/not clickable
- [ ] Join the session as a patient
- [ ] Ensure the 'client is waiting' badge shows up on the patient appointment and in the video
- [ ] Practitioner should now be able to click Admit
- [ ] Both patient and practitioner should join into the video
- [ ] Client is waiting badge should disappear from appointment
- [ ] Hang up the call

## Mobile, Browsers, Jane Desktop

- [ ] chrome
- [ ] safari
- [ ] firefox
- [ ] opera

## Regression Testing / Exploratory

## Peer Review for Moderate Risk or Higher

- [ ]  Peer Review

## Labels

- [ ]  **Portfolio Team label is added**
- [ ]  **T-shirt label is added**

## For new features and improvements to UX: Add test cases to Steve Hong's Notion Document

- [ ]  Steve has my test cases

## Pass PR in GitHub / Mark Scheduled for Release in Linear

- [ ]  Move from **Testing in Progress** to **Testing Complete** on **QA Board**
- [ ]  Move from **QA** to **Ready for Deploy** on **Roll Out Board**

**Comment by sishmail** [comment]
## Before Testing

- [ ]  CI must be passing
- [ ]  No conflicts
- [ ]  No unresolved reviews/changes requested
- [ ]  No additional changes/pushes from dev since the last round of QA
- [ ]  Release note is sufficient for [#features](https://janeapp.slack.com/archives/C0KC1395G)
- [ ]  Read through Notion / Linear Issue / Slack Convo / Demo video
- [ ]  Read through comments

## Developer's Recommended Test Plan

- [ ] Create online appts on S8 and launch the iOS app
- [ ] Please ensure that the waiting room is working properly
- [ ] Please ensure that all functionality during the call is working properly (screen sharing, text chat and video audio mute/unmute, etc.)
- [ ] Please ensure that the user can see the duration/details of the session in the "Report-> Online appointments" & "Report -> Activity" sections of the Jane admin app.

## Additional Thoughts on Testing

Admin Side:

- [ ] Settings > Treatments & Classes > Create an online treatment
- [ ] Book the online treatment into another practitioners schedule (book this in less than an hour from the time it is now).
- [ ] Click Begin
- [ ] Ensure Jane gives the "You are not authorized to join this call" message with the "Sign in as" button.
- [ ] Sign in as the correct practitioner
- [ ] Resend Email notification for the appointment - ensure this sends.
- [ ] Click Begin

Admin Side Test in Video Chat:
More actions button:

- [ ] Display name
- [ ] Manage Video Quality
- [ ] View full screen
- [ ] Settings
- [ ] Mute everyone
- [ ] Toggle Title View
- [ ] Turn camera on and off to ensure this works
- [ ] Open the chat, type a message
- [ ] Raise/Lower your hand
- [ ] Share Screen
- [ ] Hang up the call

Patient Side:

- [ ] Login as a patient and book an online appointment that is scheduled within the next hour
- [ ] Ensure you get an email notification
- [ ] Login to your account and join the appointment
- [ ] Consent to video call
- [ ] Test the same video call settings
- [ ] Camera
- [ ] Mute/Un mute
- [ ] Chat
- [ ] Test on multiple browsers to make sure this works

Waiting Room:

- [ ]Turn on waiting room beta
- [ ] Join the session as a practitioner and admit button should be grey/not clickable
- [ ] Join the session as a patient
- [ ] Ensure the 'client is waiting' badge shows up on the patient appointment and in the video
- [ ] Practitioner should now be able to click Admit
- [ ] Both patient and practitioner should join into the video
- [ ] Client is waiting badge should disappear from appointment
- [ ] Hang up the call

## Mobile, Browsers, Jane Desktop

- [ ] Chrome
- [ ] Safari
- [ ] Opera
- [ ] Firefox

## Regression Testing / Exploratory

(Consider related areas or areas where data persists Ie. Chart Templates/Intake Forms, Chart Entries/Export to PDF, Reports / Export to CSV/xls, Payment / Receipts / Superbill(US))

- Does this area have an inverse setting? Enabled/Disabled, Beta Feature Flag
- When testing emails: Have you tested both with an email on file and with no email on file, manually triggered emails (Welcome, Password Reset, Intake Form, Upcoming Appointments) and automated emails: Thanks for Booking, Cancelations, Reminders, Surveys, Telehealth, R&R, and RVR. Also, have you tried to trigger Family Relationship emails?
- Does this correspond to an area in Online Booking? (Booking an appointment, Entering a credit card and paying for an appointment)

## Peer Review for Moderate Risk or Higher

- [ ]  Peer Review

## Labels

- [x]  **Portfolio Team label is added**
- [x]  **T-shirt label is added**

## For new features and improvements to UX: Add test cases to Steve Hong's Notion Document

- [ ]  Steve has my test cases

## Pass PR in GitHub / Mark Scheduled for Release in Linear

- [ ]  Move from **Testing in Progress** to **Testing Complete** on **QA Board**
- [ ]  Move from **QA** to **Ready for Deploy** on **Roll Out Board**

**Pull request merged**
